<a href="https://colab.research.google.com/github/faznafathima/ICTAK/blob/main/ASSIGNMENT_ON_PREPROCESSING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ASSIGNMENT ON PREPROCESSING**

**DATASET: TITANIC.CSV**


---



---



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## **1. Load the dataset into the Python environment:**

In [2]:
data=pd.read_csv(r"/content/drive/MyDrive/titanic_dataset.csv")
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

## **2. Load the dataset into the Python environment:**

In [3]:
data.set_index('PassengerId', inplace=True)

## **3. Check the basic details of the dataset:**

In [4]:
# Display the first few rows of the dataset
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [5]:
# Get information about the columns and missing values
print(data.info())


<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Name      891 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Ticket    891 non-null    object 
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object 
 10  Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB
None


In [6]:
# Get statistical summary of the dataset
print(data.describe())

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200


In [8]:
data.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

Age, cabin and Embarked have missing values

## **4. Fill in all the missing values present in all the columns in the dataset:**

In [9]:
# Fill missing values in 'Age' column with the mean age
data['Age'].fillna(data['Age'].mean(), inplace=True)

# Fill missing values in 'Cabin' column with 'Unknown'
data['Cabin'].fillna('Unknown', inplace=True)

# Fill missing values in 'Embarked' column with the most common value
most_common_embarked = data['Embarked'].mode()[0]
data['Embarked'].fillna(most_common_embarked, inplace=True)

# Verify if missing values are filled
print(data.isnull().sum())


Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Cabin       0
Embarked    0
dtype: int64


## **5. Check and handle outliers in at least 3 columns in the dataset:**

In [10]:
# Let's consider 'Age', 'Fare', and 'SibSp' columns for outlier detection and handling

# Descriptive statistics before outlier handling
print("Before outlier handling:")
print(data.describe())


# Convert 'Age' column to numeric
data['Age'] = pd.to_numeric(data['Age'], errors='coerce')

# Detect and handle outliers in 'Age' column using IQR method
Q1 = data['Age'].quantile(0.25)
Q3 = data['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
data['Age'] = data['Age'].clip(lower_bound, upper_bound)

# Detect and handle outliers in 'Fare' column using IQR method
Q1 = data['Fare'].quantile(0.25)
Q3 = data['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
data['Fare'] = data['Fare'].clip(lower_bound, upper_bound)

# Detect and handle outliers in 'SibSp' column using Z-score method
mean_sibsp = data['SibSp'].mean()
std_sibsp = data['SibSp'].std()
threshold = 3
data['SibSp'] = data['SibSp'].apply(lambda x: mean_sibsp if abs(x - mean_sibsp) > threshold * std_sibsp else x)

# Verify if outliers are handled
print(data.describe())


# Verify if outliers are handled
# Descriptive statistics after outlier handling
print("\n")
print("After outlier handling:")

print(data.describe())


Before outlier handling:
         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200
         Survived      Pclass         Age      SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.00000  891.000000  891.000000
mean     0.383838    2.308642   29.376817    0.36890    0.381594   24.046813
std      0.486592    0.836071   12.062035 

In summary, the descriptive statistics before and after outlier handling demonstrate that the outlier handling methods used were effective in identifying and adjusting extreme values in the 'Age', 'Fare', and 'SibSp' columns. The handling process helps ensure that these columns have a more reasonable distribution and reduces the influence of outliers on subsequent analyses.

## **6. Perform min-max scaling on the feature set, considering 'Survived' as the target:**

In [11]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Separate the features and target variable
X = data.drop('Survived', axis=1)
y = data['Survived']

# Create a ColumnTransformer to preprocess different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', SimpleImputer(strategy='median'), ['Age', 'SibSp', 'Parch', 'Fare']),
        ('cat', SimpleImputer(strategy='most_frequent'), ['Embarked']),
        ('drop', 'drop', ['Name', 'Sex', 'Ticket', 'Cabin'])
    ])

# Perform preprocessing on the feature set
X_processed = preprocessor.fit_transform(X)

# Encode the categorical column
encoder = OneHotEncoder(sparse=False)
X_encoded = encoder.fit_transform(X_processed)

# Perform min-max scaling on the feature set
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_encoded)

# Verify the scaled feature set
print(X_scaled)


[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


The preprocessing steps, including handling missing values, one-hot encoding, and scaling, have been successfully applied to the Titanic dataset. The resulting feature set is now ready for further analysis or modeling tasks.



---



---

